services:
  staff_planner:
    build: .
    container_name: staff_planner
    ports:
      - "8890:5000"
    environment:
      - TZ=Europe/Istanbul
      - DB_URL=sqlite:////app/instance/planner.db
    volumes:
      # Veritabanını kalıcı tutmak için instance klasörü mount
      - ./instance:/app/instance
    restart: unless-stopped
